/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.13                          *
*        Compiled Nov 23 2011, 10:51:55                              *
*        (c) 2011 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

#include <string.h>
#include <stdio.h>
#include "GUI_Verventa.h"


/*********************************************************************
*
*       Defines
*
**********************************************************************
*/

#define ID_FRAMEWIN_0 (GUI_ID_USER + 0x20)
#define ID_TEXT_0 (GUI_ID_USER + 0x08)
#define ID_TEXT_1 (GUI_ID_USER + 0x09)
#define ID_TEXT_1B (GUI_ID_USER + 0x09 + 0x1000)

#define ID_TEXT_2 (GUI_ID_USER + 0x0C)
#define ID_RADIO_0 (GUI_ID_USER + 0x0D)
#define ID_SLIDER_0 (GUI_ID_USER + 0x0E)
#define ID_RADIO_1 (GUI_ID_USER + 0x10)
// #define ID_TEXT_3 (GUI_ID_USER + 0x11)
#define ID_TEXT_4 (GUI_ID_USER + 0x12)
#define ID_TEXT_4MH   (GUI_ID_USER + 0x2A0)	//':'
#define ID_TEXT_4M   (GUI_ID_USER + 0x2A1)

#define ID_BUTTON_9 (GUI_ID_USER + 0x1F)
#define ID_TEXT_5 (GUI_ID_USER + 0x20)
#define ID_CHECKBOX_0 (GUI_ID_USER + 0x21)
#define ID_TEXT_6 (GUI_ID_USER + 0x24)
#define ID_TEXT_7 (GUI_ID_USER + 0x26)
#define ID_TEXT_8 (GUI_ID_USER + 0x28)

// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

static WM_HWIN s_hCurTemp;
int32_t g_hCurTemp;

static void _cbDialog(WM_MESSAGE * pMsg);
static void _prv_AppDrawFun(void);

/*********************************************************************
*
*	Exported Data
*
**********************************************************************
*/

int g_manSetTmp;
int g_hour, g_isPM, g_min, g_dow;

bool g_secTgl;
DS_ManualCtl g_manCtl;
const PROGRAMTIME *g_pEffPgm;

enm_FanCtl g_fanCtlVal;
enm_AirCtl g_airCtlVal;

WM_HWIN hWinThermostat;
WM_HWIN hWinFanImg;

bool Touch_thermo = false;

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
	{ FRAMEWIN_CreateIndirect, "Verventa Thermostat", ID_FRAMEWIN_0, 0, 0, 320, 240, 0, 0, 0 },

	{ TEXT_CreateIndirect, "txtCurTmprt", ID_TEXT_0, 4, 80, 96, 69, 0, 100, 0 },
	// Large current effective set to temperature value
	{ TEXT_CreateIndirect, "txtEffSetToTmprt", ID_TEXT_1B, 5, 144, 80, 69, 0, 100, 0 },

	{ TEXT_CreateIndirect, "lblFanCtl", ID_TEXT_2, 180, 129, 55, 28, 0, 100, 0 },
	{ RADIO_CreateIndirect, "FanControl", ID_RADIO_0, 187, 152, 68, 55, 0, 4611, 0 },
	{ SLIDER_CreateIndirect, "SetToSlider", ID_SLIDER_0, 278, 60, 25, 147, 8, 0, 1 },
	{ RADIO_CreateIndirect, "rdo_Cndtnr", ID_RADIO_1, 187, 53, 89, 81, 0, 4612, 0 },

	// { TEXT_CreateIndirect, "txtSetToTmp", ID_TEXT_3, 254, 24, 57, 12, 0, 100, 0 },
	// Large manual set to temperature value
	{ TEXT_CreateIndirect, "SetToTmprt", ID_TEXT_1, 255, 29, 58, 37, 0, 100, 0 },


	{ TEXT_CreateIndirect, "txtRTCH", ID_TEXT_4, 4, 11, 48, 35, 0, 100, 0 },  	
	{ TEXT_CreateIndirect, "txtRTCMH", ID_TEXT_4MH, 50, 9, 16, 35, 0, 100, 0 },	// MH: MaoHao ':'
	{ TEXT_CreateIndirect, "txtRTCM", ID_TEXT_4M, 70, 11, 48, 35, 0, 100, 0 },
	{ BUTTON_CreateIndirect, "btnSetup", ID_BUTTON_9, 85, 155, 100, 45, 0, 0, 0 },	
	{ CHECKBOX_CreateIndirect, "chkManual", ID_CHECKBOX_0, 190, 8, 120, 13, 0, 0, 0 },
	{ TEXT_CreateIndirect, "txtWeekday", ID_TEXT_6, 6, 47, 75, 34, 0, 100, 0 },
	{ TEXT_CreateIndirect, "lblAirCtl", ID_TEXT_7, 189, 34, 108, 20, 0, 100, 0 },
	{ TEXT_CreateIndirect, "txtAM", ID_TEXT_8, 125, 7, 40, 20, 0, 100, 0 },
	{ TEXT_CreateIndirect, "txtPM", ID_TEXT_5, 125, 28, 33, 21, 0, 100, 0 },
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

void UpdateSetToTemperature(){
	char buf[8];
	WM_HWIN h;
	h = WM_GetDialogItem(hWinThermostat, ID_TEXT_1);	
	sprintf(buf,"%2d",g_manSetTmp);
	TEXT_SetText(h, buf);
}

void AGUI_UpdateCurTemperature(signed int f){
	WM_HWIN h;
	char buf[8];
	sprintf(buf,"%2d", f);
	TEXT_SetText(s_hCurTemp, buf);

	// update current effective set temperature (manual/program)
	h = WM_GetDialogItem(hWinThermostat, ID_TEXT_1B);
	if (g_manCtl.isEn)
	{
		sprintf(buf,"%2d",g_manSetTmp);
		TEXT_SetText(h, buf);
	}
	else
	{
		if (g_pEffPgm)
			sprintf(buf, "%2d", g_pEffPgm->temp);
		else
			sprintf(buf, "  ");
	}
	TEXT_SetText(h, buf);
}


void AGUI_ShowRTC(){
	char buf[6];
	WM_HWIN hTxtRTCH, hTxtRTCMH, hTxtRTCM, hAM, hPM, hWk;

	hTxtRTCH = WM_GetDialogItem(hWinThermostat, ID_TEXT_4);
	hTxtRTCMH = WM_GetDialogItem(hWinThermostat, ID_TEXT_4MH);
	hTxtRTCM = WM_GetDialogItem(hWinThermostat, ID_TEXT_4M);
	hAM = WM_GetDialogItem(hWinThermostat, ID_TEXT_8);
	hPM = WM_GetDialogItem(hWinThermostat, ID_TEXT_5);
	hWk = WM_GetDialogItem(hWinThermostat, ID_TEXT_6);


	buf[0] = g_hour / 10 + '0';
	buf[1] = g_hour % 10 + '0';
	buf[2] = 0;
	TEXT_SetText(hTxtRTCH, buf);
	buf[1] = g_secTgl ? ':' : ' ';
	TEXT_SetText(hTxtRTCMH, buf + 1);
	buf[0] = g_min / 10 + '0';
	buf[1] = g_min % 10 + '0';
	TEXT_SetText(hTxtRTCM, buf);

	
	if (g_isPM)
	{
		WM_HideWindow(hAM);
		WM_ShowWindow(hPM);
	}
	else
	{
		WM_HideWindow(hPM);
		WM_ShowWindow(hAM);

	}

	switch (g_dow)
	{
	case 1:
		TEXT_SetText(hWk, "Tue");
		break;
	case 2:
		TEXT_SetText(hWk, "Wed");
		break;
	case 3:
		TEXT_SetText(hWk, "Thu");
		break;
	case 4:
		TEXT_SetText(hWk, "Fri");
		break;
	case 5:
		TEXT_SetText(hWk, "Sat");
		break;
	case 6:
		TEXT_SetText(hWk, "Sun");
		break;
	default:
		TEXT_SetText(hWk, "Mon");
		break;
	}
}


/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg){
  WM_HWIN hItem;
  int Id, NCode, t1;

  switch (pMsg->MsgId) {
	  case WM_INIT_DIALOG:
		// Initialization of 'Thermostat'
		hItem = pMsg->hWin;
		FRAMEWIN_SetFont(hItem, &GUI_Font8x16);
		FRAMEWIN_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
		FRAMEWIN_SetTextColor(hItem, 0x00000000);
		// Initialization of 'txtCurRTC'
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
		TEXT_SetText(hItem, "72");
		TEXT_SetFont(hItem, GUI_FONT_D64);
		TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
		TEXT_SetTextColor(hItem, 0x00258D52);
		// Initialization of 'SetToTmprt'
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
		TEXT_SetFont(hItem, GUI_FONT_32B_ASCII);
		TEXT_SetText(hItem, "75");
		TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
		// Initialization of 'txtEffSetToTmprt'
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1B);
		TEXT_SetText(hItem, "81");
		TEXT_SetFont(hItem, GUI_FONT_D48);
		TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
		TEXT_SetTextColor(hItem, 0x008D2552);
		// Initialization of 'txtFanCtl'
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_2);
		TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_TOP);
		TEXT_SetText(hItem, "Fan");
		TEXT_SetFont(hItem, GUI_FONT_20B_ASCII);
		// Initialization of 'FanControl'
		hItem = WM_GetDialogItem(pMsg->hWin, ID_RADIO_0);
		RADIO_SetText(hItem, "Auto", 0);
		RADIO_SetText(hItem, "On", 1);
		RADIO_SetFont(hItem, GUI_FONT_16B_ASCII);
		RADIO_SetText(hItem, "Off", 2);
		// Initialization of 'rdo_Cndtnr'
		hItem = WM_GetDialogItem(pMsg->hWin, ID_RADIO_1);
		RADIO_SetText(hItem, "Auto", 0);
		RADIO_SetText(hItem, "Cooler", 1);
		RADIO_SetFont(hItem, GUI_FONT_16B_ASCII);
		RADIO_SetText(hItem, "Heater", 2);
		RADIO_SetText(hItem, "Off", 3);
		// Initialization of 'txtRTCH'
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_4);
		TEXT_SetText(hItem, "12");
		TEXT_SetFont(hItem, GUI_FONT_D24X32);
		// Initialization of 'txtRTCMH'
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_4MH);
		TEXT_SetText(hItem, ":");
		TEXT_SetFont(hItem, GUI_FONT_D24X32);
		// Initialization of 'txtRTCM'
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_4M);
		TEXT_SetText(hItem, "00");
		TEXT_SetFont(hItem, GUI_FONT_D24X32);
		// Initialization of 'btnSetup'
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_9);
		BUTTON_SetText(hItem, "Setup");
		BUTTON_SetFont(hItem, GUI_FONT_16B_ASCII);
		// Initialization of 'txtPM'
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_5);
		TEXT_SetText(hItem, "PM");
		TEXT_SetFont(hItem, GUI_FONT_24B_ASCII);
		// Initialization of 'chkManual'
		hItem = WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_0);
		CHECKBOX_SetText(hItem, "Manual control");
		CHECKBOX_SetFont(hItem, GUI_FONT_16B_ASCII);
		CHECKBOX_SetState(hItem, 1);
		g_manCtl.isEn = true;
		// Initialization of 'txtWeekday'
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_6);
		TEXT_SetFont(hItem, GUI_FONT_24B_ASCII);
		TEXT_SetText(hItem, "Wed");
		// Initialization of 'Text'
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_7);
		TEXT_SetText(hItem, "Adjust");
		TEXT_SetFont(hItem, GUI_FONT_20B_ASCII);
		// Initialization of 'txtAM'
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_8);
		TEXT_SetText(hItem, "AM");
		TEXT_SetFont(hItem, GUI_FONT_24B_ASCII);
		// Slider Init
		hItem = WM_GetDialogItem(pMsg->hWin, ID_SLIDER_0);
		SLIDER_SetRange(hItem, 0, TEMP_MAX - TEMP_MIN);
		SLIDER_SetValue(hItem, TEMP_MAX - g_manSetTmp);
		
		s_hCurTemp = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
		
		UpdateSetToTemperature();
		break;
	  
	  case WM_TOUCH:
		break;
		
	  case WM_NOTIFY_PARENT:
		Id    = WM_GetId(pMsg->hWinSrc);
		NCode = pMsg->Data.v;
		switch(Id) {
			case ID_RADIO_0: // Notifications sent by 'FanControl'
			  switch(NCode) {
				  case WM_NOTIFICATION_CLICKED:
					break;
				  case WM_NOTIFICATION_RELEASED:
					break;
				  case WM_NOTIFICATION_VALUE_CHANGED:
					hItem = WM_GetDialogItem(pMsg->hWin, ID_RADIO_0);
					t1 = RADIO_GetValue(hItem);
					g_manCtl.fanCtl = (enm_FanCtl) t1;        
					break;
				  }
			break;
			case ID_SLIDER_0: // Notifications sent by 'SetToSlider'
			  switch(NCode) {
				  case WM_NOTIFICATION_CLICKED:
					break;
				  case WM_NOTIFICATION_RELEASED:
					break;
				  case WM_NOTIFICATION_VALUE_CHANGED:
					hItem = WM_GetDialogItem(pMsg->hWin, ID_SLIDER_0);
					g_manSetTmp = TEMP_MAX - SLIDER_GetValue(hItem);
					g_manCtl.cx16setTmp = g_manSetTmp;
					UpdateSetToTemperature();
					break;
			  }
			break;
			case ID_RADIO_1: // Notifications sent by 'rdo_Cndtnr'
			  switch(NCode) {
				  case WM_NOTIFICATION_CLICKED:
					break;
				  case WM_NOTIFICATION_RELEASED:
					break;
				  case WM_NOTIFICATION_VALUE_CHANGED:
					hItem = WM_GetDialogItem(pMsg->hWin, ID_RADIO_1);
					t1 = RADIO_GetValue(hItem);
					g_manCtl.airCtl = (enm_AirCtl) t1;
					break;
			  }
			break;
			case ID_BUTTON_9: // Notifications sent by 'btnSetup'
			  switch(NCode) {
				  case WM_NOTIFICATION_CLICKED:
					break;
				  case WM_NOTIFICATION_RELEASED:
					ShowWindow(_hWindow4);
					Touch_thermo = true;
					break;
			  }
			break;
			/*case ID_CHECKBOX_0: // Notifications sent by 'chkManual'
			  switch(NCode) {
				  case WM_NOTIFICATION_CLICKED:
					break;
				  case WM_NOTIFICATION_RELEASED:
					break;
				  case WM_NOTIFICATION_VALUE_CHANGED:
					hItem = WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_0);
					g_manCtl.isEn = CHECKBOX_GetState(hItem) ? true : false;
					break;
			  }
			break;*/
		}
	  break;
	  default:
		WM_DefaultProc(pMsg);
		break;
	}
}


/*********************************************************************
*
*       Show Fan
*/
#ifdef SHOW_FAN
static void _prv_AppDrawFun(void){
	static int idx;
	
	if (g_fanCtlVal == fanctl_off)
	{
		GUI_DrawBitmap(&bmfan_Stop0, 2, 2);
		idx = 0;
	}
	else
	{	
		switch(idx++)
		{
		case 0:
			GUI_DrawBitmap(&bmfan_Rot0, 2, 2);
			break;
		case 1:
			GUI_DrawBitmap(&bmfan_Rot1, 2, 2);
			break;
		case 2:
			GUI_DrawBitmap(&bmfan_Rot2, 2, 2);
			break;		
		case 3:
			GUI_DrawBitmap(&bmfan_Rot3, 2, 2);
			idx = 0;
			break;		
		default:
			idx = 0;
		}
	}
	switch (g_airCtlVal)
	{
	case airctl_cooler:
		GUI_SetColor(0x00DFA000);
		break;
	case airctl_heater:
		GUI_SetColor(GUI_LIGHTRED);
		break;
	default:
		GUI_SetColor(0x00DFA000);
		break;
	}	
	GUI_DrawRect(0, 0, 62, 62);
	GUI_DrawRect(1, 1, 61, 61);
}

void _cbFanImg(WM_MESSAGE *pMsg){
	switch (pMsg->MsgId){
		case WM_PAINT:
			_prv_AppDrawFun();
			break;
		default:
			WM_DefaultProc(pMsg);
	}
}
#endif

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateThermostat
**********************************************************************
*/

WM_HWIN CreateThermostat(void) {
  WM_HWIN hWin;
  
  FRAMEWIN_SetDefaultSkin(FRAMEWIN_SKIN_FLEX);
  BUTTON_SetDefaultSkin(BUTTON_SKIN_FLEX);

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), &_cbDialog, WM_HBKWIN, 0, 0);
  #ifdef SHOW_FAN
	hWinFanImg = WM_CreateWindowAsChild(114, 104, 63, 63, 
		hWin,
		WM_CF_FGND | WM_CF_MEMDEV | WM_CF_SHOW,
		_cbFanImg, 0
	);
  #endif
  WM_HideWindow(hWin);
  
  return hWin;
}


/*************************** End of file ****************************/
